---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest

options:
  package_manager_path: /usr/bin/microdnf
  tags:
    - c2bmc-test

additional_build_files:
  - src: ansible.cfg
    dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

  python_interpreter:
    package_system: python3
    python_path: /usr/bin/python3

  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner


additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip